---
title: "Stein's Paradox"
output: html_notebook
---

Define variables and functions needed
```{r}
library(ggplot2)


p <- 20
eucl_len <- function(x) {
  sqrt(sum(x^2))
}


simulate <- function(means) {
  p <- length(means)
  JS_loss <- c()
  posJS_loss <- c()
  mean_shift_loss <- c()
  intuitive_loss <- c()
  lim_tr_loss <- c()
  
  for (i in 1:100){
  normal <- rnorm(p, means, 1) #Generate sample from normal distribution, independent


  ybar <- mean(normal)
  c <- 1 - (p-3)/(p-1)*var(normal)
  len_x <- eucl_len(normal)
  a <- p - 2 #minimises risk

  mean_shift <- ybar + c*(normal - ybar)
  JS <- (1 - a/len_x^2)*normal
  posJS <- 0*normal
  #lim_tr <- min(max(JS, normal - 1), normal + 1)
  if (a > len_x^2){
    posJS <- JS
  }
  

  JS_loss <- c(JS_loss, eucl_len(JS - means)^2)
  posJS_loss <- c(posJS_loss, eucl_len(posJS - means)^2)
  mean_shift_loss <- c(mean_shift_loss, eucl_len(mean_shift - means)^2)
  intuitive_loss <- c(intuitive_loss, eucl_len(normal - means)^2)
    
    
}
  x <- list()
  x[[1]] <- JS_loss
  x[[2]] <- posJS_loss
  x[[3]] <- mean_shift_loss
  x[[4]] <- intuitive_loss
  
  return(x)
}
```

```{r}
set.seed(267462)

means_unif <- runif(p, -1, 1)
unif <- simulate(means_unif)
geom_bar(unif)

```